# Generated by scripts/homebrew-formula.mjs. Do not edit by hand:
# the release workflow overwrites this file on every tag.
class TlsForge < Formula
  desc "Scraping HTTP client that sends a real browser's TLS fingerprint"
  homepage "https://github.com/Sec-CH-Lemon/tls-forge"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Sec-CH-Lemon/tls-forge/releases/download/v0.1.0/tls-forge_0.1.0_darwin_arm64.tar.gz"
      sha256 "aa1130e13dad0475a835f9f124989b9a46a595b84dc5b6b04f05f351cd03f178"
    end
    on_intel do
      url "https://github.com/Sec-CH-Lemon/tls-forge/releases/download/v0.1.0/tls-forge_0.1.0_darwin_amd64.tar.gz"
      sha256 "ec420883acc515328a6fd89f8109742f6e3bdedade9b51fdfb2154b3ecfb495e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Sec-CH-Lemon/tls-forge/releases/download/v0.1.0/tls-forge_0.1.0_linux_arm64.tar.gz"
      sha256 "0ce7d10ba6d28fdfd811ef67a0ca313f70602d0e812e6e45c7a14fc152ae82d4"
    end
    on_intel do
      url "https://github.com/Sec-CH-Lemon/tls-forge/releases/download/v0.1.0/tls-forge_0.1.0_linux_amd64.tar.gz"
      sha256 "5f149d7da886cb5fd637b9984de0581dec54f9427171831d1706f958fd80d954"
    end
  end

  def install
    bin.install "tls-forge"
    # Apache-2.0 section 4 and the licences of everything linked into the binary
    # require these to travel with it.
    pkgshare.install "LICENSE", "NOTICE", "THIRD-PARTY-NOTICES.txt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tls-forge version")

    # The point of the tool is the handshake it sends, so the test exercises it
    # rather than only checking that the binary runs. profiles reads the
    # embedded profile and prints what it can impersonate; it needs no network.
    assert_match "chrome", shell_output("#{bin}/tls-forge profiles")
  end
end
